### ISSUE TITLE
[deployment] Where to store which data?

### ISSUE THREAD

**Issue by julienschmidt** [Rostlab/JS16_ProjectD_Group4#44]
I'm still not really clear where we are supposed to store which data and how we provide data to the other Projects.

As far as I understood, we are supposed to use the same DB as Project A to save our data on characters (#20). So we should update the DB directly with our metadata on characters?

@sacdallago told us that we may use "our own" (i.e. configurable local DB?) for the Tweets. This database might get huge... up to several Gigabyte. Do we leave that up to the integration group and just provide a JS function to initialize the DB configured in the config?
Should we provide a dump of our existing crawled data?

How will our chart be integrated? We basically just need one client-side JS file and one CSS file to be included. Moreover one the init-function has the be called on one SVG-node.

The JS Script then requests CSV data. For that we need an HTTP handler available. Do we also provide just the controller function?

Anything else I forgot, @marcusnovotny @santanumohanta ?

**Comment by marcusnovotny** [comment]
Nothing to add from my side

**Comment by ghost** [comment]
As far as I understood, the twitter data we can save in our own database but need to provide the popularity/sentiment per character to A's database.

**Comment by sacdallago** [comment]
@santanumohanta is correct, just look at how [D5](https://github.com/Rostlab/JS16_ProjectD_Group5/issues) did it, they have several cross-issues with project A and some older, closed issues where these things have been discussed ;)

Anyway you got the idea: db for the tweets, provide the functions to get the sentiments to A so that they can store it on their DB and service it via API. not the cleanest solution, but we got to get to a 0.1 at some stage
