### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectD_Group4#6]
Please, **please** your code should be very, **very** well structured (indentation!!) and understandable!

This is not: https://github.com/Rostlab/JS16_ProjectD_Group4/blob/develop/crawler/twitter.js
- [ ] commenting out console.log isn't nice. Delete them
- [ ] indentation, indentation, indentation!
- [ ] your comments are not really helping me understand the code (maybe it's indentation, maybe I'm just stupid , which is perfectly possible ahahahahah )

@julienschmidt you approved that pull request. Approving pull requests is not only seeing it and merging it, a quick look at the code and some comments in case they are needed are also very accepted! :)

**Comment by julienschmidt** [comment]
Hi Christian, 
I specifically asked Santanu to make a PR with whatever he currently has, since we ran into problems with the Twitter API (see #5), we currently can only get Tweets from the last 7 days. I wanted to help him finding a solution. You wrote earlier that you want PRs so you can see who did what. That's why I merged his code first instead of just creating a branch from his dev branch. So that is my fault.

2 of us 3 are JavaScript beginners and all 3 of us never worked with node.js or mongoDB before. I wanted to help with the integration in the existing node app :wink: (see #5 again).

@santanumohanta There should be a plugin for Atom (I hope you started using it now :stuck_out_tongue_closed_eyes: ) which does auto-formatting for you. Search for something like JS / JavaScript beautifier / prettifier. Use 4 spaces for indentation. In Sublime Text you can set the indentation style in the bottom right corner, Atom should be similar:
![spacing](https://cloud.githubusercontent.com/assets/944947/13549342/41b56cc4-e303-11e5-914d-344b6bd92537.png)
It then auto-indents if you press return and <Tab> should also insert 4 spaces.
In (modern) JavaScript indentation is used instead of those `// end for` etc comments.
And preferably use `camelCaseForVariables` (which is just my personal preference, then we are consistent)

**Comment by sacdallago** [comment]
Thanks @julienschmidt for the answer! I understand :) Just wanted to point out, and yes: Autoformatters on athom, brackets, or whatever editor are your best friends.

Good luck guys! If you really get lost on coding also open up issues and assign them to us mentors ( @sacdallago, @gyachdav , @goldbergtatyana and @dmitry-n ) and we will try to help you. We won't be as quick as some of your teammates though, so it's really just for tier 2 problems (35 ppl and 11 groups to manage takes up quite some time).

:v:

**Comment by ghost** [comment]
Thanks @sacdallago  and @julienschmidt for your valuable inputs/helps !
